//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelHub.Данные
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class TravelHubEntities : DbContext
    {
        private static TravelHubEntities _context;
        public TravelHubEntities()
            : base("name=TravelHubEntities")
        {
        }
        public static TravelHubEntities GetContext()
        {
            if (_context == null)
            {
                _context = new TravelHubEntities();
            }
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }


        public virtual DbSet<Бронирование> Бронирование { get; set; }
        public virtual DbSet<Номер> Номер { get; set; }
        public virtual DbSet<Отель> Отель { get; set; }
        public virtual DbSet<Пользователь> Пользователь { get; set; }
        public virtual DbSet<Роль> Роль { get; set; }
        public virtual DbSet<Список_брони> Список_брони { get; set; }
        public virtual DbSet<Статус> Статус { get; set; }
        public virtual DbSet<Тип> Тип { get; set; }
    }
}
