//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelHub.Данные
{
    using System;
    using System.Collections.Generic;
    
    public partial class Бронирование
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Бронирование()
        {
            this.Список_брони = new HashSet<Список_брони>();
        }
    
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public int ID_Брони { get; set; }
        public Nullable<System.DateTime> Дата_заселения { get; set; }
        public Nullable<long> ID_Пользователя { get; set; }
        public Nullable<int> ID_Статуса { get; set; }
        public Nullable<int> ID_Отеля { get; set; }
        public Nullable<System.DateTime> Дата_выселения { get; set; }
        public Nullable<int> ID_Номера { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Список_брони> Список_брони { get; set; }
        public virtual Статус Статус { get; set; }
        public virtual Отель Отель { get; set; }
        public virtual Пользователь Пользователь { get; set; }
        public virtual Номер Номер { get; set; }
    }
}
