//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelHub.Данные
{
    using System;
    using System.Collections.Generic;
    
    public partial class Список_брони
    {
        public int ID_Списка_брони { get; set; }
        public Nullable<int> ID_Номера { get; set; }
        public Nullable<int> ID_Брони { get; set; }
    
        public virtual Бронирование Бронирование { get; set; }
        public virtual Номер Номер { get; set; }
    }
}
